# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='services.proto',
  package='services',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0eservices.proto\x12\x08services\"\x1b\n\x0cHelloRequest\x12\x0b\n\x03pid\x18\x01 \x01(\x05\"\x1c\n\nHelloReply\x12\x0e\n\x06retval\x18\x01 \x01(\t\"\x1b\n\x0bServiceName\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1b\n\x0bServicePort\x12\x0c\n\x04port\x18\x01 \x01(\t\")\n\x12ServiceDescription\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t2\x9f\x02\n\x07\x44oStuff\x12;\n\tsay_hello\x12\x16.services.HelloRequest\x1a\x14.services.HelloReply\"\x00\x12\x41\n\x0fsay_hello_again\x12\x16.services.HelloRequest\x1a\x14.services.HelloReply\"\x00\x12\x42\n\x10get_service_port\x12\x15.services.ServiceName\x1a\x15.services.ServicePort\"\x00\x12P\n\x17get_service_description\x12\x15.services.ServiceName\x1a\x1c.services.ServiceDescription\"\x00\x62\x06proto3'
)




_HELLOREQUEST = _descriptor.Descriptor(
  name='HelloRequest',
  full_name='services.HelloRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pid', full_name='services.HelloRequest.pid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=55,
)


_HELLOREPLY = _descriptor.Descriptor(
  name='HelloReply',
  full_name='services.HelloReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='retval', full_name='services.HelloReply.retval', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=85,
)


_SERVICENAME = _descriptor.Descriptor(
  name='ServiceName',
  full_name='services.ServiceName',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='services.ServiceName.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=114,
)


_SERVICEPORT = _descriptor.Descriptor(
  name='ServicePort',
  full_name='services.ServicePort',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='port', full_name='services.ServicePort.port', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=143,
)


_SERVICEDESCRIPTION = _descriptor.Descriptor(
  name='ServiceDescription',
  full_name='services.ServiceDescription',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='description', full_name='services.ServiceDescription.description', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=186,
)

DESCRIPTOR.message_types_by_name['HelloRequest'] = _HELLOREQUEST
DESCRIPTOR.message_types_by_name['HelloReply'] = _HELLOREPLY
DESCRIPTOR.message_types_by_name['ServiceName'] = _SERVICENAME
DESCRIPTOR.message_types_by_name['ServicePort'] = _SERVICEPORT
DESCRIPTOR.message_types_by_name['ServiceDescription'] = _SERVICEDESCRIPTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQUEST,
  '__module__' : 'services_pb2'
  # @@protoc_insertion_point(class_scope:services.HelloRequest)
  })
_sym_db.RegisterMessage(HelloRequest)

HelloReply = _reflection.GeneratedProtocolMessageType('HelloReply', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREPLY,
  '__module__' : 'services_pb2'
  # @@protoc_insertion_point(class_scope:services.HelloReply)
  })
_sym_db.RegisterMessage(HelloReply)

ServiceName = _reflection.GeneratedProtocolMessageType('ServiceName', (_message.Message,), {
  'DESCRIPTOR' : _SERVICENAME,
  '__module__' : 'services_pb2'
  # @@protoc_insertion_point(class_scope:services.ServiceName)
  })
_sym_db.RegisterMessage(ServiceName)

ServicePort = _reflection.GeneratedProtocolMessageType('ServicePort', (_message.Message,), {
  'DESCRIPTOR' : _SERVICEPORT,
  '__module__' : 'services_pb2'
  # @@protoc_insertion_point(class_scope:services.ServicePort)
  })
_sym_db.RegisterMessage(ServicePort)

ServiceDescription = _reflection.GeneratedProtocolMessageType('ServiceDescription', (_message.Message,), {
  'DESCRIPTOR' : _SERVICEDESCRIPTION,
  '__module__' : 'services_pb2'
  # @@protoc_insertion_point(class_scope:services.ServiceDescription)
  })
_sym_db.RegisterMessage(ServiceDescription)



_DOSTUFF = _descriptor.ServiceDescriptor(
  name='DoStuff',
  full_name='services.DoStuff',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=189,
  serialized_end=476,
  methods=[
  _descriptor.MethodDescriptor(
    name='say_hello',
    full_name='services.DoStuff.say_hello',
    index=0,
    containing_service=None,
    input_type=_HELLOREQUEST,
    output_type=_HELLOREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='say_hello_again',
    full_name='services.DoStuff.say_hello_again',
    index=1,
    containing_service=None,
    input_type=_HELLOREQUEST,
    output_type=_HELLOREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='get_service_port',
    full_name='services.DoStuff.get_service_port',
    index=2,
    containing_service=None,
    input_type=_SERVICENAME,
    output_type=_SERVICEPORT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='get_service_description',
    full_name='services.DoStuff.get_service_description',
    index=3,
    containing_service=None,
    input_type=_SERVICENAME,
    output_type=_SERVICEDESCRIPTION,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DOSTUFF)

DESCRIPTOR.services_by_name['DoStuff'] = _DOSTUFF

# @@protoc_insertion_point(module_scope)
